// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVDealerDbContext.Models;

public partial class Order
{
    public Guid Id { get; set; }

    public string OrderNumber { get; set; }

    public Guid CustomerId { get; set; }

    public Guid DealerId { get; set; }

    public Guid VehicleId { get; set; }

    public decimal TotalAmount { get; set; }

    public string Status { get; set; }

    public string PaymentStatus { get; set; }

    public string Notes { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User Customer { get; set; }

    public virtual Dealer Dealer { get; set; }

    public virtual ICollection<OrderHistory> OrderHistories { get; set; } = new List<OrderHistory>();

    public virtual Vehicle Vehicle { get; set; }
}