// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVDealerDbContext.Models;

public partial class OrderHistory
{
    public Guid Id { get; set; }

    public Guid OrderId { get; set; }

    public string Status { get; set; }

    public string Notes { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual Order Order { get; set; }
}